version: "3.8"
services:
  api: 
    container_name: catalogus_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: catalogus_db
      DATABASE_USER: catalogus_user
      DATABASE_PASSWORD: catalogus_password
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
  postgres:
    image: postgres:15-alpine
    container_name: postgres_catalogus
    environment:
      POSTGRES_DB: catalogus_db
      POSTGRES_USER: catalogus_user
      POSTGRES_PASSWORD: catalogus_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U catalogus_user -d catalogus_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres_data: